### ISSUE TITLE
Works only once

### ISSUE THREAD

**Issue by fabiokr** [roidrage/crumble#2] opened 2009-08-28 14:39 UTC
Maybe I'm missing something, but I'm having this strange behavior:
The breadcumbs are only printed on the first time the helper 'crumbs' is executed.
Any posterior calls returns "". Posterior calls to Breadcrumb.instance.trails returns nil.
Any thoughts?

**Comment by roidrage** [comment] 2009-08-28 15:47
I just tried it, and it's working as it's supposed to on my end.

Where did you put yours breadcrumbs definition?

**Comment by fabiokr** [comment] 2009-08-28 15:56
/config/initializers/breadcumbs.rb
I'm using rails 2.3.3

**Comment by roidrage** [comment] 2009-08-28 15:57
And it happens when you call crumble in your views? In development mode only or production mode too?

**Comment by fabiokr** [comment] 2009-08-28 17:24
Only on development mode. Maybe rails doesn't reload the initializers on each request on dev mode? Doesn't this happens in your dev mode to?

**Comment by roidrage** [comment] 2009-08-28 17:31
Rails in fact doesn't reload the initializers on every request, but it also doesn't reload the plugins, so the class from there should still be valid and configured, unless you have a class Breadcrumb in your project which might be a problem methings. They're only loaded once and when you restart the application. I've tried it with both Mongrel and Passenger in development mode. Two subsequent calls to `crumbs` returns the trail correctly each time, same for subsequent requests.

**Comment by fabiokr** [comment] 2009-08-29 13:35
This is my project that's using your breadcumb plugin: http://github.com/fabiokr/personal-scrum/tree/master

**Comment by roidrage** [comment] 2009-08-29 13:44
I think the issue is that you're setting config.reload_plugins = true in development mode. That's very likely to be the problem. The initializers in turn aren't reloaded, so you end up with an empty breadcrumbs configuration.

**Comment by fabiokr** [comment] 2009-08-29 13:52
Thanks! That fixed it!

**Comment by roidrage** [comment] 2009-08-30 10:35
Updated readme some more. Closed by 9f937826465caa91a08c8c4b47939f8c94e6e628

**Closed as completed by roidrage** 2009-08-30 10:35 UTC
